version: "3.9"  # optional since v1.27.0
services:
  guillotine-cms:
    build:
      context: '../../'
      dockerfile: './deployments/docker/Dockerfile'
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    links:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.12.0